config/routes.rb
Tourney::Application.routes.draw do
  
  resources :applications, only: [:create, :destroy, :show, :accept, :reject] do
    member do
      post :accept
      post :reject
    end
  end
  resources :invitations, only: [:create, :destroy, :show, :accept, :decline] do
    member do
      post :accept
      post :decline
    end
  end

  resources :vacancies, only: [:create, :destroy, :show]
  resources :memberships, only: [:create, :destroy]
  resources :roles

  resources :tournaments

  resources :teams do
    member do
      get :members
    end
  end

  resources :players do
    member do
      get :invitations
      get :invite
    end
  end

  
  resource :session, only: [:new, :create, :destroy]

  root 'home#welcome'

  

  

end

app/models/tournament.rb
# == Schema Information
#
# Table name: tournaments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Tournament < ActiveRecord::Base

  validates :name, presence: true
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tournament }
      else
        format.html { render action: 'new' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.slim
= form_for(@tournament) do |f|
  - if @tournament.errors.any?
    #error_explanation
      h2
        = pluralize(@tournament.errors.count, "error")
        | prohibited this tournament from being saved:
      ul
        - @tournament.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :name
    br/
    = f.text_field :name
  .actions
    = f.submit

app/views/tournaments/edit.html.slim
h1 Editing tournament
= render 'form'
= link_to 'Show', @tournament
| \
| \#{link_to 'Back', tournaments_path}

app/views/tournaments/index.html.slim
h1 Listing tournaments
table
  thead
    tr
      th Name
      th
      th
      th
  tbody
    - @tournaments.each do |tournament|
      tr
        td= tournament.name
        td= link_to 'Show', tournament
        td= link_to 'Edit', edit_tournament_path(tournament)
        td= link_to 'Destroy', tournament, method: :delete, confirm: 'Are you sure?'  
br/
= link_to 'New Tournament', new_tournament_path

app/views/tournaments/new.html.slim
h1 New tournament
= render 'form'
= link_to 'Back', tournaments_path

app/views/tournaments/show.html.slim
p#notice= notice
p
  strong Name:
  = @tournament.name
= link_to 'Edit', edit_tournament_path(@tournament)
| \
| \#{link_to 'Back', tournaments_path}