config/routes.rb
Tourney::Application.routes.draw do
  
  resources :applications, only: [:create, :destroy, :show, :accept, :reject] do
    member do
      post :accept
      post :reject
    end
  end
  resources :invitations, only: [:create, :destroy, :show, :accept, :decline] do
    member do
      post :accept
      post :decline
    end
  end

  resources :vacancies, only: [:create, :destroy, :show]
  resources :memberships, only: [:create, :destroy]
  resources :roles

  resources :tournaments

  resources :teams do
    member do
      get :members
    end
  end

  resources :players do
    member do
      get :invitations
      get :invite
    end
  end

  
  resource :session, only: [:new, :create, :destroy]

  root 'home#welcome'

  

  

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id              :integer          not null, primary key
#  nick            :string(255)
#  first_name      :string(255)
#  last_name       :string(255)
#  country         :string(255)
#  birth_date      :date
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class Player < ActiveRecord::Base

  validates :nick, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :country, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, uniqueness: true
  validates :birth_date, presence: true

  has_secure_password

  has_many :teams
  has_many :memberships

  has_many :invitations
  has_many :applications

  def pending_invitations
    invitations.where(status: Invitation.SENT)
  end
  def declined_invitations
    invitations.where(status: Invitation.DECLINED)
  end

  def is_member?(team)
    memberships.find_by(team_id: team.id) #or teams.find_by(id: team.id)
  end

  def join!(team, role)
    memberships.create!(team_id: team.id, role_id: role.id)
  end

  def leave!(team)
    memberships.find_by(team_id: team.id).destroy!
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy, :invitations, :invite]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @memberships = @player.memberships
    @teams = @player.teams

    if current_user
      @not_teams = current_user.teams.where.not(id: @teams.pluck(:id))
    end
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  def invitations
    @invitations = @player.invitations
  end

  def invite
    @invitation = Invitation.new
    @teams = @player.teams
    @not_teams = current_user.teams.where.not(id: @teams.pluck(:id))

    if @not_teams.count == 0
      back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:nick, :password, :password_confirmation, :first_name, :last_name, :country, :birth_date, :email)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.slim
= form_for(@player) do |f|
  - if @player.errors.any?
    #error_explanation
      h2
        = pluralize(@player.errors.count, "error")
        | prohibited this player from being saved:
      ul
        - @player.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :nick
    br/
    = f.text_field :nick
  .field
    = f.label :password
    br/
    = f.password_field :password
  .field
    = f.label :password_confirmation
    br/
    = f.password_field :password_confirmation
    br/
  /!
    | <div class="field"
    | </haml:block><haml:silent></haml:silent><haml:block><br
    | <haml:silent
    | </haml:silent>  </div
  strong Personal Information
  .field
    = f.label :first_name
    br/
    = f.text_field :first_name
  .field
    = f.label :last_name
    br/
    = f.text_field :last_name
  .field
    = f.label :country
    br/
    = f.text_field :country
  .field
    = f.label :birth_date
    br/
    = f.date_select :birth_date, start_year: Time.now.year - 100, end_year: Time.now.year, use_short_month: true
  .field
    = f.label :email
    br/
    = f.text_field :email
  .actions
    = f.submit 'Create Account'

app/views/players/edit.html.slim
h1 Editing player
= render 'form'
= link_to 'Show', @player
| \
| \#{link_to 'Back', players_path}

app/views/players/index.html.slim
h1 Listing players
table
  thead
    tr
      th Nick
      th Country
      th First name
      th Last name
      th
      th
      th
  tbody
    - @players.each do |player|
      tr
        td= player.nick
        td= player.country
        td= player.first_name
        td= player.last_name
        td= link_to 'Show', player
        td= link_to 'Edit', edit_player_path(player)
        td= link_to 'Destroy', player, method: :delete, confirm: 'Are you sure?'  
br
= link_to 'New Player', new_player_path

app/views/players/invitations.html.slim
h1= @player.nick
h2 Invitations
hr/
- if @invitations.count > 0
  table
    thead
      tr
        th Team
        th Role
        th Message
        th Date
        th
        th
    tbody
      - @invitations.each do |inv|
        tr
          - team = inv.team
          td= link_to team.short_name, team_path(team)
          td= inv.role_s
          td= inv.message
          td= inv.created_at
          - if current_user.id == inv.player_id
            td= link_to "Accept", accept_invitation_path(inv), method: :post
            td= link_to "Reject", decline_invitation_path(inv), method: :post
- else
  p You have no invitations.

app/views/players/invite.html.slim
/! <h1></haml:block><haml:silent></haml:silent><haml:block></h1
h1
  | Invitation for #{@player.nick}
  = form_for(@invitation) do |f|
    - if @invitation.errors.any?
      #error_explanation
        h2
          = pluralize(@invitation.errors.count, "error")
          | prohibited this invitation from being saved:
        ul
          - @invitation.errors.full_messages.each do |msg|
            li= msg
    .field
      = f.label :team
      br/
      = f.collection_select(:team_id, @not_teams, :id, :name)
    .field
      = f.label :role
      br/
      = f.collection_select(:role_id, Role.all, :id, :name)
    .field
      = f.label :message
      br/
      = f.text_area :message
    .field
      = f.hidden_field :player_id, :value => @player.id
    .field
      = f.hidden_field :status, :value => Invitation.SENT
    .actions
      = f.submit 'Send Invitation'

app/views/players/new.html.slim
h1 New Player
= render 'form'
= link_to 'Back', players_path

app/views/players/show.html.slim
#notice
  = notice
.info
  h1
    = @player.nick
  - if current_user and @not_teams.count > 0
    = link_to 'Invite to team', invite_player_path(@player)
  .personal-info
    p
      = @player.first_name + ' ' + @player.last_name
    p
      = @player.country
    p
      = @player.birth_date
    p
      = @player.email
  .team-info
    - if @teams.length > 0
      h2
        | Captain of:
      ul
        - @teams.each do |team|
          li
            = link_to team.name, team_path(team)
    - if @memberships.length > 0
      h2
        | Member of:
      ul
        - @memberships.each do |membership|
          - team = membership.team
          li
            = link_to team.name, team_path(team)
            - if membership.role
              | \- #{membership.role.name}
    - else
      p Belongs to no teams
= link_to 'Edit', edit_player_path(@player)
= link_to 'Back', players_path