config/routes.rb
Tourney::Application.routes.draw do
  
  resources :applications, only: [:create, :destroy, :show, :accept, :reject] do
    member do
      post :accept
      post :reject
    end
  end
  resources :invitations, only: [:create, :destroy, :show, :accept, :decline] do
    member do
      post :accept
      post :decline
    end
  end

  resources :vacancies, only: [:create, :destroy, :show]
  resources :memberships, only: [:create, :destroy]
  resources :roles

  resources :tournaments

  resources :teams do
    member do
      get :members
    end
  end

  resources :players do
    member do
      get :invitations
      get :invite
    end
  end

  
  resource :session, only: [:new, :create, :destroy]

  root 'home#welcome'

  

  

end

app/models/application.rb
# == Schema Information
#
# Table name: applications
#
#  id            :integer          not null, primary key
#  player_id     :integer
#  status        :integer
#  message       :text
#  created_at    :datetime
#  updated_at    :datetime
#  invitation_id :integer
#  vacancy_id    :integer
#

class Application < ActiveRecord::Base

  @@SENT = 1
  @@ACCEPTED = 2
  @@REJECTED = 0

  validates :vacancy_id, presence: true
  validates :player_id, presence: true
  validates :status, presence: true, inclusion: [@@SENT, @@ACCEPTED, @@REJECTED]

  belongs_to :player
  belongs_to :vacancy

  def self.SENT
    @@SENT
  end
  def self.ACCEPTED
    @@ACCEPTED
  end
  def self.REJECTED
    @@REJECTED
  end

  def accept
    membership = Membership.new(player_id: player_id, team_id: vacancy.team_id)
    membership.role = vacancy.role
    membership.save
  end
end

app/models/invitation.rb
# == Schema Information
#
# Table name: invitations
#
#  id         :integer          not null, primary key
#  team_id    :integer
#  player_id  :integer
#  status     :integer
#  message    :text
#  created_at :datetime
#  updated_at :datetime
#

class Invitation < ActiveRecord::Base
  @@SENT = 1
  @@ACCEPTED = 2
  @@DECLINED = 0

  validates :team_id, presence: true
  validates :player_id, presence: true
  validates :status, presence: true, inclusion: [@@SENT, @@ACCEPTED, @@DECLINED]

  belongs_to :player
  belongs_to :team
  belongs_to :role

  def self.SENT
    @@SENT
  end
  def self.ACCEPTED
    @@ACCEPTED
  end
  def self.DECLINED
    @@DECLINED
  end
  
  def role_s
    if role
      role.name
    else
      'Any role'
    end
  end
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id         :integer          not null, primary key
#  player_id  :integer
#  team_id    :integer
#  role_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Membership < ActiveRecord::Base
  belongs_to :player
  belongs_to :team
  belongs_to :role

  validates :player_id, presence: true
  validates :team_id, presence: true
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id              :integer          not null, primary key
#  nick            :string(255)
#  first_name      :string(255)
#  last_name       :string(255)
#  country         :string(255)
#  birth_date      :date
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class Player < ActiveRecord::Base

  validates :nick, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :country, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, uniqueness: true
  validates :birth_date, presence: true

  has_secure_password

  has_many :teams
  has_many :memberships

  has_many :invitations
  has_many :applications

  def pending_invitations
    invitations.where(status: Invitation.SENT)
  end
  def declined_invitations
    invitations.where(status: Invitation.DECLINED)
  end

  def is_member?(team)
    memberships.find_by(team_id: team.id) #or teams.find_by(id: team.id)
  end

  def join!(team, role)
    memberships.create!(team_id: team.id, role_id: role.id)
  end

  def leave!(team)
    memberships.find_by(team_id: team.id).destroy!
  end

end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Role < ActiveRecord::Base
  validates :name, presence: true
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  short_name :string(255)
#  created_at :datetime
#  updated_at :datetime
#  player_id  :integer
#

class Team < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  validates :short_name, presence: true, uniqueness: true #, length: {in: 1..10}

  validates :player_id, presence: true

  belongs_to :player
  
  has_many :memberships
  has_many :players, through: :memberships

  has_many :vacancies
  has_many :invitations
  has_many :applications

  def recruit(player, role)
    player.join!(self, role)
  end

  def expel(player)
    player.leave!(self)
  end
end

app/models/tournament.rb
# == Schema Information
#
# Table name: tournaments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Tournament < ActiveRecord::Base

  validates :name, presence: true
end

app/models/vacancy.rb
# == Schema Information
#
# Table name: vacancies
#
#  id           :integer          not null, primary key
#  team_id      :integer
#  role_id      :integer
#  created_at   :datetime
#  updated_at   :datetime
#  requirements :text
#

class Vacancy < ActiveRecord::Base

  validates :team_id, presence: true

  belongs_to :team
  belongs_to :role

  has_many :applications

  def pending_applications
    applications.where(status: Application.SENT)
  end
  def accepted_applications
    applications.where(status: Application.ACCEPTED)
  end
  def rejected_applications
    applications.where(status: Application.REJECTED)
  end

  def role_s
    if role
      role.name
    else
      'Any role'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(controller)
    return params[:controller] == controller.underscore
  end 
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "danger"}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar 
        span.icon-bar
        span.icon-bar

      = link_to 'Home', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-left
        /== render 'layouts/navigation_links'
        
        li class=('active' if is_active?('players')) = link_to 'Players', players_path
        li class=('active' if is_active?('teams')) = link_to 'Teams', teams_path
        li class=('active' if is_active?('tournaments')) = link_to 'Tournaments', tournaments_path

      ul.nav.navbar-nav.navbar-right        
        - if current_user
            li = link_to current_user.pending_invitations.count.to_s + ' Invitations', invitations_player_path(current_user)
            li = link_to current_user.nick, player_path(current_user)
            li = link_to 'Sign out', session_path, :method => :delete
        - else
            li = link_to 'Sign up', new_player_path
            li = link_to 'Log in', new_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Tourney'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Tourney'}"
    == stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield